services:
    - docker:dind

stages:
    - test
    - build
    - deploy

# Run flake8 to check for code quality
# And also optionally run unit tests
tests:
    image: python:3-bullseye
    stage: test
    script:
        - pip install flake8
        - flake8 api
        # Run unit tests
        - cd api
        - pip install -r requirements.txt
        - python -m pytest
